const data = {
    products: [
      {
        _id: '1',
        name: 'Grey Basin Tap',
        category: 'Plumbing',
        image: './images/grey_basin_tap.jpg ',
        price: 800,
        countInStock: 10,
        brand: 'Cera',
        rating: 4.5,
        numReviews: 15,
        description: 'Wash Basin Mixer tap',
      },

      {
        _id: '2',
        name: 'kitchen Tap',
        category: 'Plumbing',
        image: './images/kitchen_mixer.jpeg',
        price: 500,
        countInStock: 10,
        brand: 'Cera',
        rating: 5,
        numReviews: 10,
        description: 'Kitchen Wash Basin Mixer tap',
      },
      {
        _id: '3',
        name: 'Wash Basin',
        category: 'Plumbing',
        image: './images/ceramic_washbasin.jpg',
        price: 2500,
        countInStock: 10,
        brand: 'Hindware',
        rating: 4.5,
        numReviews: 20,
        description: 'Ceramic washbasin',
      },
      {
        _id: '4',
        name: 'Modern Wash basin',
        category: 'Plumbing',
        image: './images/Baasin.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Somany',
        rating: 4.5,
        numReviews: 10,
        description: 'Stylish stone basin for living room',
      },
      {
        _id: '5',
        name: 'parking tiles(1pc)',
        category: 'Tiles',
        image: './images/parking-tiles.jpeg',
        price: 25,
        countInStock: 0,
        brand: 'Ivory Neo',
        rating: 3.5,
        numReviews: 10,
        description: 'Thickness: 14 mm, Size: 305x305 mm.',
      },
      {
        _id: '6',
        name: 'Modren Car Parking tiles(1pc)',
        category: 'Tiles',
        image: './images/car_parking_tiles.jpg',
        price: 120,
        countInStock: 20,
        brand: 'Ivory Neo',
        rating: 4.5,
        numReviews: 10,
        description: 'Thickness: 14 mm, Size: 305x305 mm.',
      },
      
      
    ],
  };
  export default data;
